tushar-kumar/HacktoberFest2022

- Codes/traprainwater.cpp
Rainwater trapping problem: Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining
> Added traprainwater.cpp

- Codes/frequency_of_words.py
PLease assign hacktoberfest-accepted tag to it
> Frequency of words in python

- Codes/11_Container_With_Most_Water.cpp
Solution and pseudocode to the following question
Given n non-negative integers a1, a2, ..., an , where each represents a point at coordinate (i, ai). n vertical lines are drawn such that the two endpoints of the line i is at (i, ai) and (i, 0). Find two lines, which, together with the x-axis forms a container, such that the container contains the most water. Notice that you may not slant the container.
> 11_Container_With_Most_Water.cpp

- Codes/voice.py
- Matrix.py
Program to record voice using python.
> Added voice.py

- Prims_py.ipynb
> Prims Algorithm in Python

- Codes/Merge_and Quick_Sort.cpp
I have made submission for merge and quick sort in the cpp language , under the Codes section. Kindly merge my PR.
> Create Merge_and Quick_Sort.cpp

- Codes/digital_clock.py
> digital_clock.py

- Codes/combofnumbersandstar.py
Python Code of a combination of numbers and stars pattern
> Combination of numbers and stars pattern

- Codes/multiply_sum_matrix.c
Contributing as part of Hacktoberfest 2022. 
Fixes issue #21
> Find the product and sum of two matrices

- Bank Management System/login.java
If, allowed will also code for how one can check account details after login
> Uploaded code in Java for the Login Page

- Codes/MergeSort.java
- Codes/QuickSort.java
This pull request contains Quick sort and Merge sort algorithm implemented in JAVA.
> Qucik Sort and Merge Sort Algorithm added

- 368. Largest_Divisible_Subset.cpp
Leetcode Problem Largest Divisible Subset
> Create 368. Largest_Divisible_Subset.cpp

- MaximumProductSubarray.cpp
Leetcode dynamic programming question 152 , Maximum product subarray.
please merge my pull request.
> MaximumProductSubarray.cpp

- productandsum.py
please merge my code into your repository
> added product and sum of matrix

- 174. dungeon_game.cpp
Leetcode hard problem dungeon game
> Create 174. dungeon_game.cpp

- 1300-1500CodeforcesQuestions/Question1.cpp
- 1300-1500CodeforcesQuestions/Question10.cpp
- 1300-1500CodeforcesQuestions/Question2.cpp
- 1300-1500CodeforcesQuestions/Question3.cpp
- 1300-1500CodeforcesQuestions/Question4.cpp
- 1300-1500CodeforcesQuestions/Question5.cpp
- 1300-1500CodeforcesQuestions/Question6.cpp
- 1300-1500CodeforcesQuestions/Question7.cpp
- 1300-1500CodeforcesQuestions/Question8.cpp
- 1300-1500CodeforcesQuestions/Question9.cpp
I have added 10 codeforces questions related to graph theory and added comments wherever necessary.
> Added Codeforces 1300-1500 Graph Questions

- Matrix Chain Multiplication.cpp
Hello, This Problem is done in O(n^3). Plz add my PR.
> Matrix Chain Multiplication

- Bank Management System/BankTransfer.java
- Bank Management System/Customer.java
some files related to bank is added
> Bank Transfer and Customer file added

- search_2d_matrix.cpp
Write an efficient algorithm that searches for a value target in an m x n integer matrix matrix. This matrix has the following properties:
Integers in each row are sorted from left to right. The first integer of each row is greater than the last integer of the previous row.
> Created search_2d_matrix.cpp

- Dynamic Programming/0-1Knapsnack.cpp
- Dynamic Programming/LongestCommonSubstring.cpp
- Dynamic Programming/boxStacking.cpp
- Dynamic Programming/buyAndSellStocks.cpp
- Dynamic Programming/cf-1637B_MEX_and_Array.cpp
- Dynamic Programming/cf-coinRows.cpp
- Dynamic Programming/climbStairsInMinMoves.cpp
- Dynamic Programming/climbStairsWithJumps.cpp
- Dynamic Programming/climbingStairs.cpp
- Dynamic Programming/coinChange.cpp
- Dynamic Programming/countBinaryStrings.cpp
- Dynamic Programming/countSubsequencea+b+c+.cpp
- Dynamic Programming/fibonacci.cpp
- Dynamic Programming/friendsPairing.cpp
- Dynamic Programming/frogJump.cpp
- Dynamic Programming/frogJumpKdistance.cpp
- Dynamic Programming/goldmine.cpp
- Dynamic Programming/kadanesAlgo.cpp
- Dynamic Programming/longestCommonSubsequence.cpp
- Dynamic Programming/longestIncreasingSubsequence.cpp
- Dynamic Programming/maxSumNonAdjacentSubseq.cpp
- Dynamic Programming/minCostPath2D.cpp
- Dynamic Programming/paintFence.cpp
- Dynamic Programming/paintHouse1.cpp
- Dynamic Programming/paintHouse2_manyColors.cpp
- Dynamic Programming/palindromic_substring.cpp
- Dynamic Programming/partitionIntoSubset.cpp
- Dynamic Programming/stringEncoding.cpp
- Dynamic Programming/targetSumSubset.cpp
- Dynamic Programming/tilingWithDominos.cpp
@tushar-kumar  kindly check the files and merge this commit. resolved issue #59
> Add dynamic Programming problems (Resolved issue #59)

- Codes/First.cpp
> Added First.cpp file

- integertoroman.java
please merge my code into your repository
> added leetcode problem of integer to  roman

- find maximum rectangle in matrix.cpp
I create a new file for the solution of maximum rectangle in matrix suing DP. Please accept my pull Request.
> Create find maximum rectangle in matrix.cpp
